plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.4'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.ko.playground'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(23)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	implementation 'org.springframework.boot:spring-boot-starter-security'
	
	// Redis Session
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.session:spring-session-data-redis'

	// DB
	implementation 'software.amazon.jdbc:aws-advanced-jdbc-wrapper:2.5.3'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'com.h2database:h2'
	testImplementation 'junit:junit:4.13.1'
	testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}

tasks.named('test') {
	useJUnitPlatform()
}

task generatePackageInfo(type: JavaExec) {
	group = 'build setup'
	description = 'Generate package-info.java files in all Java packages'

	classpath = sourceSets.main.runtimeClasspath
	mainClass = 'com.ko.playground.basic.support.PackageInfoGenerator'

	doFirst {
		args = [file('src/main/java').absolutePath]
	}
}

