spring:
  application:
    name: "basic"
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        # IN?? ???? ??
        default_batch_fetch_size: 100